---
- hosts: all
  become: true
  tasks:
    # Ubuntu tasks
    - name: install apache and php packages on Ubtunu
      package:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: no
      when: ansible_distribuation == "Ubuntu"

    # CentOS tasks 
- name: install apache and php packages on Centos
      package:
        name:
          - httpd
          - php
        state: latest
        update_cache: no
      when: ansible_distribuation == "CentOS"

