---
- hosts: all
  become: true
  pre_tasks:

    # Update_section
  - name: install update (Centos)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Centos"

  - name: install update (Ubutnu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages on Ubtunu
    tags: apache,apache2,ubutnu
    package:
          name:
            - apache2
            - libapache2-mod-php
          state: latest
    when: ansible_distribuation == "Ubuntu"


  - name: install apache and php packages on Centos
    tags: apache,httpd,centos
    package:
          name:
            - httpd
            - php
          state: latest
    when: ansible_distribuation == "CentOS"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb (Centos)
    tags: centos,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribuation == "CentOS"

  - name: install mariadb (Ubuntu)
    tags: db,mariadb,ubuntu
    dnf:
      name: mariadb-server
      state: latest
    when: ansible_distribuation == "Ubutnu"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
